# Generated by Django 5.0.2 on 2024-06-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[
                ('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=20),
        ),
    ]
