# Generated by Django 5.0.2 on 2024-06-19 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0004_alter_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
    ]
