# Generated by Django 5.0.2 on 2024-06-19 22:32

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0005_remove_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='NULL', max_length=2),
        ),
    ]
