# Generated by Django 5.0.2 on 2024-06-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0010_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
